resource ACUSTOMERICON Icon C:\CAVO28\CUSTOMER.ICO
CLASS ACUSTOMERICON INHERIT Icon
METHOD Init() CLASS ACUSTOMERICON
   super:init(ResourceID{"ACUSTOMERICON", _GetInst()})
CLASS BOOKE2ICO INHERIT Icon
resource BOOKE2ICO Icon C:\CAVO28\BOOK.ICO
METHOD Init() CLASS BOOKE2ICO
   super:init(ResourceID{"BOOKE2ICO", _GetInst()})
CLASS EMPLOYEEICON INHERIT Icon
resource EMPLOYEEICON Icon C:\CAVO28\EMPLOYEE.ICO
METHOD Init() CLASS EMPLOYEEICON
   super:init(ResourceID{"EMPLOYEEICON", _GetInst()})
CLASS FINGERCURSOR INHERIT Pointer
resource FINGERCURSOR Cursor C:\CAVO28\FINGER.CUR
METHOD Init() CLASS FINGERCURSOR
   super:init(ResourceID{"FINGERCURSOR", _GetInst()})
resource ICONONE Icon C:\CAVO28\ONE.ICO
CLASS ICONONE INHERIT Icon
METHOD Init() CLASS ICONONE
   super:init(ResourceID{"ICONONE", _GetInst()})
CLASS ICONTWO INHERIT Icon
resource ICONTWO Icon C:\CAVO28\TWO.ICO
METHOD Init() CLASS ICONTWO
   super:init(ResourceID{"ICONTWO", _GetInst()})
resource INVOICEICON Icon C:\CAVO28\INVOICE.ICO
CLASS INVOICEICON INHERIT Icon
METHOD Init() CLASS INVOICEICON
   super:init(ResourceID{"INVOICEICON", _GetInst()})
resource ITEMICON Icon C:\CAVO28\ITEM.ICO
CLASS ITEMICON INHERIT Icon
METHOD Init() CLASS ITEMICON
   super:init(ResourceID{"ITEMICON", _GetInst()})
resource LOCKEDBITMAP BITMAP C:\CAVO28\LOCKED.BMP
CLASS OBOOKE2ICO INHERIT Icon
resource OBOOKE2ICO Icon C:\CAVO28\OBOOK.ICO
METHOD Init() CLASS OBOOKE2ICO
   super:init(ResourceID{"OBOOKE2ICO", _GetInst()})
CLASS ORDERICON INHERIT Icon
resource ORDERICON Icon C:\CAVO28\ADVORDER.ICO
METHOD Init() CLASS ORDERICON
   super:init(ResourceID{"ORDERICON", _GetInst()})
resource PASSWORDICON Icon C:\CAVO28\PASSWORD.ICO
CLASS PASSWORDICON INHERIT Icon
METHOD Init() CLASS PASSWORDICON
   super:init(ResourceID{"PASSWORDICON", _GetInst()})
CLASS PAYMENTICON INHERIT Icon
resource PAYMENTICON Icon C:\CAVO28\PAYMENT.ICO
METHOD Init() CLASS PAYMENTICON
   super:init(ResourceID{"PAYMENTICON", _GetInst()})
CLASS REMOVE_RECORD INHERIT Icon
resource REMOVE_RECORD Icon C:\CAVO28\REMRECRD.ICO
METHOD Init() CLASS REMOVE_RECORD
   super:init(ResourceID{"REMOVE_RECORD", _GetInst()})
CLASS SSABITMAP INHERIT Bitmap 
resource SSABITMAP BITMAP C:\CAVO28\SSA.BMP
METHOD Init() CLASS SSABITMAP

	SUPER:Init( ResourceID{ "SSABITMAP", _GetInst() } )

	RETURN SELF
resource SSAICON Icon C:\CAVO28\SSA.ICO
CLASS SSAICON INHERIT Icon
METHOD Init() CLASS SSAICON
   super:init(ResourceID{"SSAICON", _GetInst()})
resource UNLOCKEDBITMAP BITMAP C:\CAVO28\UNLOCKED.BMP
resource WATCHCURSOR Cursor C:\CAVO28\WATCH.CUR
CLASS WATCHCURSOR INHERIT Pointer
METHOD Init() CLASS WATCHCURSOR
   super:init(ResourceID{"WATCHCURSOR", _GetInst()})
